package com.ylzbrt.dstb.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Ky60 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY60.AAB301
     *
     * @mbg.generated
     */
    private String aab301;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY60.AAA027
     *
     * @mbg.generated
     */
    private String aaa027;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY60.BAE033
     *
     * @mbg.generated
     */
    private String bae033;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY60.AKB020
     *
     * @mbg.generated
     */
    private String akb020;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY60.AKB021
     *
     * @mbg.generated
     */
    private String akb021;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY60.AKB022
     *
     * @mbg.generated
     */
    private String akb022;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY60.AAE006
     *
     * @mbg.generated
     */
    private String aae006;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY60.AAB034
     *
     * @mbg.generated
     */
    private String aab034;

    @Override
    public String toString() {
        return "Ky60{" +
                "aab301='" + aab301 + '\'' +
                ", aaa027='" + aaa027 + '\'' +
                ", bae033='" + bae033 + '\'' +
                ", akb020='" + akb020 + '\'' +
                ", akb021='" + akb021 + '\'' +
                ", akb022='" + akb022 + '\'' +
                ", aae006='" + aae006 + '\'' +
                ", aab034='" + aab034 + '\'' +
                ", aae035=" + aae035 +
                ", gxlsh0=" + gxlsh0 +
                '}';
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY60.AAE035
     *
     * @mbg.generated
     */
    private Date aae035;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column KY60.GXLSH0
     *
     * @mbg.generated
     */
    private BigDecimal gxlsh0;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY60.AAB301
     *
     * @return the value of KY60.AAB301
     *
     * @mbg.generated
     */
    public String getAab301() {
        return aab301;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY60.AAB301
     *
     * @param aab301 the value for KY60.AAB301
     *
     * @mbg.generated
     */
    public void setAab301(String aab301) {
        this.aab301 = aab301 == null ? null : aab301.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY60.AAA027
     *
     * @return the value of KY60.AAA027
     *
     * @mbg.generated
     */
    public String getAaa027() {
        return aaa027;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY60.AAA027
     *
     * @param aaa027 the value for KY60.AAA027
     *
     * @mbg.generated
     */
    public void setAaa027(String aaa027) {
        this.aaa027 = aaa027 == null ? null : aaa027.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY60.BAE033
     *
     * @return the value of KY60.BAE033
     *
     * @mbg.generated
     */
    public String getBae033() {
        return bae033;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY60.BAE033
     *
     * @param bae033 the value for KY60.BAE033
     *
     * @mbg.generated
     */
    public void setBae033(String bae033) {
        this.bae033 = bae033 == null ? null : bae033.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY60.AKB020
     *
     * @return the value of KY60.AKB020
     *
     * @mbg.generated
     */
    public String getAkb020() {
        return akb020;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY60.AKB020
     *
     * @param akb020 the value for KY60.AKB020
     *
     * @mbg.generated
     */
    public void setAkb020(String akb020) {
        this.akb020 = akb020 == null ? null : akb020.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY60.AKB021
     *
     * @return the value of KY60.AKB021
     *
     * @mbg.generated
     */
    public String getAkb021() {
        return akb021;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY60.AKB021
     *
     * @param akb021 the value for KY60.AKB021
     *
     * @mbg.generated
     */
    public void setAkb021(String akb021) {
        this.akb021 = akb021 == null ? null : akb021.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY60.AKB022
     *
     * @return the value of KY60.AKB022
     *
     * @mbg.generated
     */
    public String getAkb022() {
        return akb022;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY60.AKB022
     *
     * @param akb022 the value for KY60.AKB022
     *
     * @mbg.generated
     */
    public void setAkb022(String akb022) {
        this.akb022 = akb022 == null ? null : akb022.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY60.AAE006
     *
     * @return the value of KY60.AAE006
     *
     * @mbg.generated
     */
    public String getAae006() {
        return aae006;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY60.AAE006
     *
     * @param aae006 the value for KY60.AAE006
     *
     * @mbg.generated
     */
    public void setAae006(String aae006) {
        this.aae006 = aae006 == null ? null : aae006.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY60.AAB034
     *
     * @return the value of KY60.AAB034
     *
     * @mbg.generated
     */
    public String getAab034() {
        return aab034;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY60.AAB034
     *
     * @param aab034 the value for KY60.AAB034
     *
     * @mbg.generated
     */
    public void setAab034(String aab034) {
        this.aab034 = aab034 == null ? null : aab034.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY60.AAE035
     *
     * @return the value of KY60.AAE035
     *
     * @mbg.generated
     */
    public Date getAae035() {
        return aae035;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY60.AAE035
     *
     * @param aae035 the value for KY60.AAE035
     *
     * @mbg.generated
     */
    public void setAae035(Date aae035) {
        this.aae035 = aae035;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column KY60.GXLSH0
     *
     * @return the value of KY60.GXLSH0
     *
     * @mbg.generated
     */
    public BigDecimal getGxlsh0() {
        return gxlsh0;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column KY60.GXLSH0
     *
     * @param gxlsh0 the value for KY60.GXLSH0
     *
     * @mbg.generated
     */
    public void setGxlsh0(BigDecimal gxlsh0) {
        this.gxlsh0 = gxlsh0;
    }
}