package com.ylzbrt.dstb.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class Ky60Example {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table KY60
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table KY60
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table KY60
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KY60
     *
     * @mbg.generated
     */
    public Ky60Example() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KY60
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KY60
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KY60
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KY60
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KY60
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KY60
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KY60
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KY60
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KY60
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KY60
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table KY60
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAab301IsNull() {
            addCriterion("AAB301 is null");
            return (Criteria) this;
        }

        public Criteria andAab301IsNotNull() {
            addCriterion("AAB301 is not null");
            return (Criteria) this;
        }

        public Criteria andAab301EqualTo(String value) {
            addCriterion("AAB301 =", value, "aab301");
            return (Criteria) this;
        }

        public Criteria andAab301NotEqualTo(String value) {
            addCriterion("AAB301 <>", value, "aab301");
            return (Criteria) this;
        }

        public Criteria andAab301GreaterThan(String value) {
            addCriterion("AAB301 >", value, "aab301");
            return (Criteria) this;
        }

        public Criteria andAab301GreaterThanOrEqualTo(String value) {
            addCriterion("AAB301 >=", value, "aab301");
            return (Criteria) this;
        }

        public Criteria andAab301LessThan(String value) {
            addCriterion("AAB301 <", value, "aab301");
            return (Criteria) this;
        }

        public Criteria andAab301LessThanOrEqualTo(String value) {
            addCriterion("AAB301 <=", value, "aab301");
            return (Criteria) this;
        }

        public Criteria andAab301Like(String value) {
            addCriterion("AAB301 like", value, "aab301");
            return (Criteria) this;
        }

        public Criteria andAab301NotLike(String value) {
            addCriterion("AAB301 not like", value, "aab301");
            return (Criteria) this;
        }

        public Criteria andAab301In(List<String> values) {
            addCriterion("AAB301 in", values, "aab301");
            return (Criteria) this;
        }

        public Criteria andAab301NotIn(List<String> values) {
            addCriterion("AAB301 not in", values, "aab301");
            return (Criteria) this;
        }

        public Criteria andAab301Between(String value1, String value2) {
            addCriterion("AAB301 between", value1, value2, "aab301");
            return (Criteria) this;
        }

        public Criteria andAab301NotBetween(String value1, String value2) {
            addCriterion("AAB301 not between", value1, value2, "aab301");
            return (Criteria) this;
        }

        public Criteria andAaa027IsNull() {
            addCriterion("AAA027 is null");
            return (Criteria) this;
        }

        public Criteria andAaa027IsNotNull() {
            addCriterion("AAA027 is not null");
            return (Criteria) this;
        }

        public Criteria andAaa027EqualTo(String value) {
            addCriterion("AAA027 =", value, "aaa027");
            return (Criteria) this;
        }

        public Criteria andAaa027NotEqualTo(String value) {
            addCriterion("AAA027 <>", value, "aaa027");
            return (Criteria) this;
        }

        public Criteria andAaa027GreaterThan(String value) {
            addCriterion("AAA027 >", value, "aaa027");
            return (Criteria) this;
        }

        public Criteria andAaa027GreaterThanOrEqualTo(String value) {
            addCriterion("AAA027 >=", value, "aaa027");
            return (Criteria) this;
        }

        public Criteria andAaa027LessThan(String value) {
            addCriterion("AAA027 <", value, "aaa027");
            return (Criteria) this;
        }

        public Criteria andAaa027LessThanOrEqualTo(String value) {
            addCriterion("AAA027 <=", value, "aaa027");
            return (Criteria) this;
        }

        public Criteria andAaa027Like(String value) {
            addCriterion("AAA027 like", value, "aaa027");
            return (Criteria) this;
        }

        public Criteria andAaa027NotLike(String value) {
            addCriterion("AAA027 not like", value, "aaa027");
            return (Criteria) this;
        }

        public Criteria andAaa027In(List<String> values) {
            addCriterion("AAA027 in", values, "aaa027");
            return (Criteria) this;
        }

        public Criteria andAaa027NotIn(List<String> values) {
            addCriterion("AAA027 not in", values, "aaa027");
            return (Criteria) this;
        }

        public Criteria andAaa027Between(String value1, String value2) {
            addCriterion("AAA027 between", value1, value2, "aaa027");
            return (Criteria) this;
        }

        public Criteria andAaa027NotBetween(String value1, String value2) {
            addCriterion("AAA027 not between", value1, value2, "aaa027");
            return (Criteria) this;
        }

        public Criteria andBae033IsNull() {
            addCriterion("BAE033 is null");
            return (Criteria) this;
        }

        public Criteria andBae033IsNotNull() {
            addCriterion("BAE033 is not null");
            return (Criteria) this;
        }

        public Criteria andBae033EqualTo(String value) {
            addCriterion("BAE033 =", value, "bae033");
            return (Criteria) this;
        }

        public Criteria andBae033NotEqualTo(String value) {
            addCriterion("BAE033 <>", value, "bae033");
            return (Criteria) this;
        }

        public Criteria andBae033GreaterThan(String value) {
            addCriterion("BAE033 >", value, "bae033");
            return (Criteria) this;
        }

        public Criteria andBae033GreaterThanOrEqualTo(String value) {
            addCriterion("BAE033 >=", value, "bae033");
            return (Criteria) this;
        }

        public Criteria andBae033LessThan(String value) {
            addCriterion("BAE033 <", value, "bae033");
            return (Criteria) this;
        }

        public Criteria andBae033LessThanOrEqualTo(String value) {
            addCriterion("BAE033 <=", value, "bae033");
            return (Criteria) this;
        }

        public Criteria andBae033Like(String value) {
            addCriterion("BAE033 like", value, "bae033");
            return (Criteria) this;
        }

        public Criteria andBae033NotLike(String value) {
            addCriterion("BAE033 not like", value, "bae033");
            return (Criteria) this;
        }

        public Criteria andBae033In(List<String> values) {
            addCriterion("BAE033 in", values, "bae033");
            return (Criteria) this;
        }

        public Criteria andBae033NotIn(List<String> values) {
            addCriterion("BAE033 not in", values, "bae033");
            return (Criteria) this;
        }

        public Criteria andBae033Between(String value1, String value2) {
            addCriterion("BAE033 between", value1, value2, "bae033");
            return (Criteria) this;
        }

        public Criteria andBae033NotBetween(String value1, String value2) {
            addCriterion("BAE033 not between", value1, value2, "bae033");
            return (Criteria) this;
        }

        public Criteria andAkb020IsNull() {
            addCriterion("AKB020 is null");
            return (Criteria) this;
        }

        public Criteria andAkb020IsNotNull() {
            addCriterion("AKB020 is not null");
            return (Criteria) this;
        }

        public Criteria andAkb020EqualTo(String value) {
            addCriterion("AKB020 =", value, "akb020");
            return (Criteria) this;
        }

        public Criteria andAkb020NotEqualTo(String value) {
            addCriterion("AKB020 <>", value, "akb020");
            return (Criteria) this;
        }

        public Criteria andAkb020GreaterThan(String value) {
            addCriterion("AKB020 >", value, "akb020");
            return (Criteria) this;
        }

        public Criteria andAkb020GreaterThanOrEqualTo(String value) {
            addCriterion("AKB020 >=", value, "akb020");
            return (Criteria) this;
        }

        public Criteria andAkb020LessThan(String value) {
            addCriterion("AKB020 <", value, "akb020");
            return (Criteria) this;
        }

        public Criteria andAkb020LessThanOrEqualTo(String value) {
            addCriterion("AKB020 <=", value, "akb020");
            return (Criteria) this;
        }

        public Criteria andAkb020Like(String value) {
            addCriterion("AKB020 like", value, "akb020");
            return (Criteria) this;
        }

        public Criteria andAkb020NotLike(String value) {
            addCriterion("AKB020 not like", value, "akb020");
            return (Criteria) this;
        }

        public Criteria andAkb020In(List<String> values) {
            addCriterion("AKB020 in", values, "akb020");
            return (Criteria) this;
        }

        public Criteria andAkb020NotIn(List<String> values) {
            addCriterion("AKB020 not in", values, "akb020");
            return (Criteria) this;
        }

        public Criteria andAkb020Between(String value1, String value2) {
            addCriterion("AKB020 between", value1, value2, "akb020");
            return (Criteria) this;
        }

        public Criteria andAkb020NotBetween(String value1, String value2) {
            addCriterion("AKB020 not between", value1, value2, "akb020");
            return (Criteria) this;
        }

        public Criteria andAkb021IsNull() {
            addCriterion("AKB021 is null");
            return (Criteria) this;
        }

        public Criteria andAkb021IsNotNull() {
            addCriterion("AKB021 is not null");
            return (Criteria) this;
        }

        public Criteria andAkb021EqualTo(String value) {
            addCriterion("AKB021 =", value, "akb021");
            return (Criteria) this;
        }

        public Criteria andAkb021NotEqualTo(String value) {
            addCriterion("AKB021 <>", value, "akb021");
            return (Criteria) this;
        }

        public Criteria andAkb021GreaterThan(String value) {
            addCriterion("AKB021 >", value, "akb021");
            return (Criteria) this;
        }

        public Criteria andAkb021GreaterThanOrEqualTo(String value) {
            addCriterion("AKB021 >=", value, "akb021");
            return (Criteria) this;
        }

        public Criteria andAkb021LessThan(String value) {
            addCriterion("AKB021 <", value, "akb021");
            return (Criteria) this;
        }

        public Criteria andAkb021LessThanOrEqualTo(String value) {
            addCriterion("AKB021 <=", value, "akb021");
            return (Criteria) this;
        }

        public Criteria andAkb021Like(String value) {
            addCriterion("AKB021 like", value, "akb021");
            return (Criteria) this;
        }

        public Criteria andAkb021NotLike(String value) {
            addCriterion("AKB021 not like", value, "akb021");
            return (Criteria) this;
        }

        public Criteria andAkb021In(List<String> values) {
            addCriterion("AKB021 in", values, "akb021");
            return (Criteria) this;
        }

        public Criteria andAkb021NotIn(List<String> values) {
            addCriterion("AKB021 not in", values, "akb021");
            return (Criteria) this;
        }

        public Criteria andAkb021Between(String value1, String value2) {
            addCriterion("AKB021 between", value1, value2, "akb021");
            return (Criteria) this;
        }

        public Criteria andAkb021NotBetween(String value1, String value2) {
            addCriterion("AKB021 not between", value1, value2, "akb021");
            return (Criteria) this;
        }

        public Criteria andAkb022IsNull() {
            addCriterion("AKB022 is null");
            return (Criteria) this;
        }

        public Criteria andAkb022IsNotNull() {
            addCriterion("AKB022 is not null");
            return (Criteria) this;
        }

        public Criteria andAkb022EqualTo(String value) {
            addCriterion("AKB022 =", value, "akb022");
            return (Criteria) this;
        }

        public Criteria andAkb022NotEqualTo(String value) {
            addCriterion("AKB022 <>", value, "akb022");
            return (Criteria) this;
        }

        public Criteria andAkb022GreaterThan(String value) {
            addCriterion("AKB022 >", value, "akb022");
            return (Criteria) this;
        }

        public Criteria andAkb022GreaterThanOrEqualTo(String value) {
            addCriterion("AKB022 >=", value, "akb022");
            return (Criteria) this;
        }

        public Criteria andAkb022LessThan(String value) {
            addCriterion("AKB022 <", value, "akb022");
            return (Criteria) this;
        }

        public Criteria andAkb022LessThanOrEqualTo(String value) {
            addCriterion("AKB022 <=", value, "akb022");
            return (Criteria) this;
        }

        public Criteria andAkb022Like(String value) {
            addCriterion("AKB022 like", value, "akb022");
            return (Criteria) this;
        }

        public Criteria andAkb022NotLike(String value) {
            addCriterion("AKB022 not like", value, "akb022");
            return (Criteria) this;
        }

        public Criteria andAkb022In(List<String> values) {
            addCriterion("AKB022 in", values, "akb022");
            return (Criteria) this;
        }

        public Criteria andAkb022NotIn(List<String> values) {
            addCriterion("AKB022 not in", values, "akb022");
            return (Criteria) this;
        }

        public Criteria andAkb022Between(String value1, String value2) {
            addCriterion("AKB022 between", value1, value2, "akb022");
            return (Criteria) this;
        }

        public Criteria andAkb022NotBetween(String value1, String value2) {
            addCriterion("AKB022 not between", value1, value2, "akb022");
            return (Criteria) this;
        }

        public Criteria andAae006IsNull() {
            addCriterion("AAE006 is null");
            return (Criteria) this;
        }

        public Criteria andAae006IsNotNull() {
            addCriterion("AAE006 is not null");
            return (Criteria) this;
        }

        public Criteria andAae006EqualTo(String value) {
            addCriterion("AAE006 =", value, "aae006");
            return (Criteria) this;
        }

        public Criteria andAae006NotEqualTo(String value) {
            addCriterion("AAE006 <>", value, "aae006");
            return (Criteria) this;
        }

        public Criteria andAae006GreaterThan(String value) {
            addCriterion("AAE006 >", value, "aae006");
            return (Criteria) this;
        }

        public Criteria andAae006GreaterThanOrEqualTo(String value) {
            addCriterion("AAE006 >=", value, "aae006");
            return (Criteria) this;
        }

        public Criteria andAae006LessThan(String value) {
            addCriterion("AAE006 <", value, "aae006");
            return (Criteria) this;
        }

        public Criteria andAae006LessThanOrEqualTo(String value) {
            addCriterion("AAE006 <=", value, "aae006");
            return (Criteria) this;
        }

        public Criteria andAae006Like(String value) {
            addCriterion("AAE006 like", value, "aae006");
            return (Criteria) this;
        }

        public Criteria andAae006NotLike(String value) {
            addCriterion("AAE006 not like", value, "aae006");
            return (Criteria) this;
        }

        public Criteria andAae006In(List<String> values) {
            addCriterion("AAE006 in", values, "aae006");
            return (Criteria) this;
        }

        public Criteria andAae006NotIn(List<String> values) {
            addCriterion("AAE006 not in", values, "aae006");
            return (Criteria) this;
        }

        public Criteria andAae006Between(String value1, String value2) {
            addCriterion("AAE006 between", value1, value2, "aae006");
            return (Criteria) this;
        }

        public Criteria andAae006NotBetween(String value1, String value2) {
            addCriterion("AAE006 not between", value1, value2, "aae006");
            return (Criteria) this;
        }

        public Criteria andAab034IsNull() {
            addCriterion("AAB034 is null");
            return (Criteria) this;
        }

        public Criteria andAab034IsNotNull() {
            addCriterion("AAB034 is not null");
            return (Criteria) this;
        }

        public Criteria andAab034EqualTo(String value) {
            addCriterion("AAB034 =", value, "aab034");
            return (Criteria) this;
        }

        public Criteria andAab034NotEqualTo(String value) {
            addCriterion("AAB034 <>", value, "aab034");
            return (Criteria) this;
        }

        public Criteria andAab034GreaterThan(String value) {
            addCriterion("AAB034 >", value, "aab034");
            return (Criteria) this;
        }

        public Criteria andAab034GreaterThanOrEqualTo(String value) {
            addCriterion("AAB034 >=", value, "aab034");
            return (Criteria) this;
        }

        public Criteria andAab034LessThan(String value) {
            addCriterion("AAB034 <", value, "aab034");
            return (Criteria) this;
        }

        public Criteria andAab034LessThanOrEqualTo(String value) {
            addCriterion("AAB034 <=", value, "aab034");
            return (Criteria) this;
        }

        public Criteria andAab034Like(String value) {
            addCriterion("AAB034 like", value, "aab034");
            return (Criteria) this;
        }

        public Criteria andAab034NotLike(String value) {
            addCriterion("AAB034 not like", value, "aab034");
            return (Criteria) this;
        }

        public Criteria andAab034In(List<String> values) {
            addCriterion("AAB034 in", values, "aab034");
            return (Criteria) this;
        }

        public Criteria andAab034NotIn(List<String> values) {
            addCriterion("AAB034 not in", values, "aab034");
            return (Criteria) this;
        }

        public Criteria andAab034Between(String value1, String value2) {
            addCriterion("AAB034 between", value1, value2, "aab034");
            return (Criteria) this;
        }

        public Criteria andAab034NotBetween(String value1, String value2) {
            addCriterion("AAB034 not between", value1, value2, "aab034");
            return (Criteria) this;
        }

        public Criteria andAae035IsNull() {
            addCriterion("AAE035 is null");
            return (Criteria) this;
        }

        public Criteria andAae035IsNotNull() {
            addCriterion("AAE035 is not null");
            return (Criteria) this;
        }

        public Criteria andAae035EqualTo(Date value) {
            addCriterion("AAE035 =", value, "aae035");
            return (Criteria) this;
        }

        public Criteria andAae035NotEqualTo(Date value) {
            addCriterion("AAE035 <>", value, "aae035");
            return (Criteria) this;
        }

        public Criteria andAae035GreaterThan(Date value) {
            addCriterion("AAE035 >", value, "aae035");
            return (Criteria) this;
        }

        public Criteria andAae035GreaterThanOrEqualTo(Date value) {
            addCriterion("AAE035 >=", value, "aae035");
            return (Criteria) this;
        }

        public Criteria andAae035LessThan(Date value) {
            addCriterion("AAE035 <", value, "aae035");
            return (Criteria) this;
        }

        public Criteria andAae035LessThanOrEqualTo(Date value) {
            addCriterion("AAE035 <=", value, "aae035");
            return (Criteria) this;
        }

        public Criteria andAae035In(List<Date> values) {
            addCriterion("AAE035 in", values, "aae035");
            return (Criteria) this;
        }

        public Criteria andAae035NotIn(List<Date> values) {
            addCriterion("AAE035 not in", values, "aae035");
            return (Criteria) this;
        }

        public Criteria andAae035Between(Date value1, Date value2) {
            addCriterion("AAE035 between", value1, value2, "aae035");
            return (Criteria) this;
        }

        public Criteria andAae035NotBetween(Date value1, Date value2) {
            addCriterion("AAE035 not between", value1, value2, "aae035");
            return (Criteria) this;
        }

        public Criteria andGxlsh0IsNull() {
            addCriterion("GXLSH0 is null");
            return (Criteria) this;
        }

        public Criteria andGxlsh0IsNotNull() {
            addCriterion("GXLSH0 is not null");
            return (Criteria) this;
        }

        public Criteria andGxlsh0EqualTo(BigDecimal value) {
            addCriterion("GXLSH0 =", value, "gxlsh0");
            return (Criteria) this;
        }

        public Criteria andGxlsh0NotEqualTo(BigDecimal value) {
            addCriterion("GXLSH0 <>", value, "gxlsh0");
            return (Criteria) this;
        }

        public Criteria andGxlsh0GreaterThan(BigDecimal value) {
            addCriterion("GXLSH0 >", value, "gxlsh0");
            return (Criteria) this;
        }

        public Criteria andGxlsh0GreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("GXLSH0 >=", value, "gxlsh0");
            return (Criteria) this;
        }

        public Criteria andGxlsh0LessThan(BigDecimal value) {
            addCriterion("GXLSH0 <", value, "gxlsh0");
            return (Criteria) this;
        }

        public Criteria andGxlsh0LessThanOrEqualTo(BigDecimal value) {
            addCriterion("GXLSH0 <=", value, "gxlsh0");
            return (Criteria) this;
        }

        public Criteria andGxlsh0In(List<BigDecimal> values) {
            addCriterion("GXLSH0 in", values, "gxlsh0");
            return (Criteria) this;
        }

        public Criteria andGxlsh0NotIn(List<BigDecimal> values) {
            addCriterion("GXLSH0 not in", values, "gxlsh0");
            return (Criteria) this;
        }

        public Criteria andGxlsh0Between(BigDecimal value1, BigDecimal value2) {
            addCriterion("GXLSH0 between", value1, value2, "gxlsh0");
            return (Criteria) this;
        }

        public Criteria andGxlsh0NotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("GXLSH0 not between", value1, value2, "gxlsh0");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table KY60
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table KY60
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}