package com.ylzbrt.dstb.dao;

import com.ylzbrt.dstb.entity.Ky60;
import com.ylzbrt.dstb.entity.Ky60Example;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.sql.SQLException;
import java.util.List;
import java.util.Map;

@Mapper
@Repository
public interface Ky60Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KY60
     *
     * @mbg.generated
     */
    int insert(Ky60 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KY60
     *
     * @mbg.generated
     */
    int insertSelective(Ky60 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KY60
     *
     * @mbg.generated
     */
    List<Ky60> selectByExample(Ky60Example example);

    void testReturnResult(Map mm) throws SQLException;
}